LANG_CODES = {
    "American":            "en_US",
    "English":             "en_GB",
    "Spanish":             "es_ES",
    "Mexican Spanish":     "es_MX",
    "Brazilian Portuguese":"pt_BR",
    "German":              "de_DE",
    "Cologne German":      "de_KO",
    "Dutch":               "nl_NL",
    "Turkish":             "tr_TR",
    "Afrikaans":           "af_ZA",
    "Romanian":            "ro_RO",
    "Russian":             "ru_RU",
    "Simplified Chinese":  "zh_CN",
    "Traditional Chinese": "zh_TW",
    "Thai":                "th_TH",
    "Venezuelan Spanish":  "es_VE",
    "Argentinian Spanish": "es_AR",
    "Vietnamese":          "vi_VN",
    "Australian English":  "en_AU",
}

# All translatable keys:
ALL_KEYS = [
    # Language options:
    *LANG_CODES.keys(),
    # GUI labels:
    "Language",
    "Select language",
    "OK",
    "Cancel",
    "Exit",
    "Apply",
    "Yes",
    "No",
]

TRANSLATIONS = {
    # ---- ENGLISH ----
    "en_US": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
    },
    "en_GB": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
    },
    "en_AU": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
    },
    # ---- ROMANIAN ----
    "ro_RO": {
        "American": "Americană",
        "English": "Engleză",
        "Spanish": "Spaniolă",
        "Mexican Spanish": "Spaniolă mexicană",
        "Brazilian Portuguese": "Portugheză braziliană",
        "German": "Germană",
        "Cologne German": "Germană din Köln",
        "Dutch": "Olandeză",
        "Turkish": "Turcă",
        "Afrikaans": "Afrikaans",
        "Romanian": "Română",
        "Russian": "Rusă",
        "Simplified Chinese": "Chineză simplificată",
        "Traditional Chinese": "Chineză tradițională",
        "Thai": "Thailandeză",
        "Venezuelan Spanish": "Spaniolă venezueleană",
        "Argentinian Spanish": "Spaniolă argentiniană",
        "Vietnamese": "Vietnameză",
        "Australian English": "Engleză australiană",
        "Language": "Limbă",
        "Select language": "Selectează limba",
        "OK": "OK",
        "Cancel": "Anulează",
        "Exit": "Ieșire",
        "Apply": "Aplică",
        "Yes": "Da",
        "No": "Nu",
    },
    # ---- GERMAN ----
    "de_DE": {
        "American": "Amerikanisches Englisch",
        "English": "Englisch",
        "Spanish": "Spanisch",
        "Mexican Spanish": "Mexikanisches Spanisch",
        "Brazilian Portuguese": "Brasilianisches Portugiesisch",
        "German": "Deutsch",
        "Cologne German": "Kölsch",
        "Dutch": "Niederländisch",
        "Turkish": "Türkisch",
        "Afrikaans": "Afrikaans",
        "Romanian": "Rumänisch",
        "Russian": "Russisch",
        "Simplified Chinese": "Vereinfachtes Chinesisch",
        "Traditional Chinese": "Traditionelles Chinesisch",
        "Thai": "Thailändisch",
        "Venezuelan Spanish": "Venezolanisches Spanisch",
        "Argentinian Spanish": "Argentinisches Spanisch",
        "Vietnamese": "Vietnamesisch",
        "Australian English": "Australisches Englisch",
        "Language": "Sprache",
        "Select language": "Sprache auswählen",
        "OK": "OK",
        "Cancel": "Abbrechen",
        "Exit": "Beenden",
        "Apply": "Übernehmen",
        "Yes": "Ja",
        "No": "Nein",
    },
    # ---- SPANISH (SPAIN) ----
    "es_ES": {
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
    },
    # ---- MEXICAN SPANISH ----
    "es_MX": {
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
    },
    # ---- BRAZILIAN PORTUGUESE ----
    "pt_BR": {
        "American": "Inglês americano",
        "English": "Inglês britânico",
        "Spanish": "Espanhol",
        "Mexican Spanish": "Espanhol mexicano",
        "Brazilian Portuguese": "Português brasileiro",
        "German": "Alemão",
        "Cologne German": "Alemão de Colônia",
        "Dutch": "Holandês",
        "Turkish": "Turco",
        "Afrikaans": "Africâner",
        "Romanian": "Romeno",
        "Russian": "Russo",
        "Simplified Chinese": "Chinês simplificado",
        "Traditional Chinese": "Chinês tradicional",
        "Thai": "Tailandês",
        "Venezuelan Spanish": "Espanhol venezuelano",
        "Argentinian Spanish": "Espanhol argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglês australiano",
        "Language": "Idioma",
        "Select language": "Selecionar idioma",
        "OK": "OK",
        "Cancel": "Cancelar",
        "Exit": "Sair",
        "Apply": "Aplicar",
        "Yes": "Sim",
        "No": "Não",
    },
    # ---- DUTCH ----
    "nl_NL": {
        "American": "Amerikaans Engels",
        "English": "Brits Engels",
        "Spanish": "Spaans",
        "Mexican Spanish": "Mexicaans Spaans",
        "Brazilian Portuguese": "Braziliaans Portugees",
        "German": "Duits",
        "Cologne German": "Keuls",
        "Dutch": "Nederlands",
        "Turkish": "Turks",
        "Afrikaans": "Afrikaans",
        "Romanian": "Roemeens",
        "Russian": "Russisch",
        "Simplified Chinese": "Vereenvoudigd Chinees",
        "Traditional Chinese": "Traditioneel Chinees",
        "Thai": "Thais",
        "Venezuelan Spanish": "Venezolaans Spaans",
        "Argentinian Spanish": "Argentijns Spaans",
        "Vietnamese": "Vietnamees",
        "Australian English": "Australisch Engels",
        "Language": "Taal",
        "Select language": "Selecteer taal",
        "OK": "OK",
        "Cancel": "Annuleren",
        "Exit": "Afsluiten",
        "Apply": "Toepassen",
        "Yes": "Ja",
        "No": "Nee",
    },
    # ---- TURKISH ----
    "tr_TR": {
        "American": "Amerikan İngilizcesi",
        "English": "İngilizce",
        "Spanish": "İspanyolca",
        "Mexican Spanish": "Meksika İspanyolcası",
        "Brazilian Portuguese": "Brezilya Portekizcesi",
        "German": "Almanca",
        "Cologne German": "Köln Almancası",
        "Dutch": "Felemenkçe",
        "Turkish": "Türkçe",
        "Afrikaans": "Afrikanca",
        "Romanian": "Rumence",
        "Russian": "Rusça",
        "Simplified Chinese": "Basitleştirilmiş Çince",
        "Traditional Chinese": "Geleneksel Çince",
        "Thai": "Tayca",
        "Venezuelan Spanish": "Venezuela İspanyolcası",
        "Argentinian Spanish": "Arjantin İspanyolcası",
        "Vietnamese": "Vietnamca",
        "Australian English": "Avustralya İngilizcesi",
        "Language": "Dil",
        "Select language": "Dil seçin",
        "OK": "Tamam",
        "Cancel": "İptal",
        "Exit": "Çıkış",
        "Apply": "Uygula",
        "Yes": "Evet",
        "No": "Hayır",
    },
    # ---- AFRIKAANS ----
    "af_ZA": {
        "American": "Amerikaanse Engels",
        "English": "Britse Engels",
        "Spanish": "Spaans",
        "Mexican Spanish": "Meksikaanse Spaans",
        "Brazilian Portuguese": "Brasiliaanse Portugees",
        "German": "Duits",
        "Cologne German": "Keuls",
        "Dutch": "Nederlands",
        "Turkish": "Turks",
        "Afrikaans": "Afrikaans",
        "Romanian": "Roemeens",
        "Russian": "Russies",
        "Simplified Chinese": "Vereenvoudigde Sjinees",
        "Traditional Chinese": "Tradisionele Sjinees",
        "Thai": "Thai",
        "Venezuelan Spanish": "Venezolaanse Spaans",
        "Argentinian Spanish": "Argentynse Spaans",
        "Vietnamese": "Viëtnamees",
        "Australian English": "Australiese Engels",
        "Language": "Taal",
        "Select language": "Kies taal",
        "OK": "OK",
        "Cancel": "Kanselleer",
        "Exit": "Verlaat",
        "Apply": "Pas toe",
        "Yes": "Ja",
        "No": "Nee",
    },
    # ---- RUSSIAN ----
    "ru_RU": {
        "American": "Американский английский",
        "English": "Британский английский",
        "Spanish": "Испанский",
        "Mexican Spanish": "Мексиканский испанский",
        "Brazilian Portuguese": "Бразильский португальский",
        "German": "Немецкий",
        "Cologne German": "Кёльнский диалект",
        "Dutch": "Голландский",
        "Turkish": "Турецкий",
        "Afrikaans": "Африкаанс",
        "Romanian": "Румынский",
        "Russian": "Русский",
        "Simplified Chinese": "Упрощённый китайский",
        "Traditional Chinese": "Традиционный китайский",
        "Thai": "Тайский",
        "Venezuelan Spanish": "Венесуэльский испанский",
        "Argentinian Spanish": "Аргентинский испанский",
        "Vietnamese": "Вьетнамский",
        "Australian English": "Австралийский английский",
        "Language": "Язык",
        "Select language": "Выберите язык",
        "OK": "ОК",
        "Cancel": "Отмена",
        "Exit": "Выход",
        "Apply": "Применить",
        "Yes": "Да",
        "No": "Нет",
    },
    # ---- SIMPLIFIED CHINESE ----
    "zh_CN": {
        "American": "美式英语",
        "English": "英式英语",
        "Spanish": "西班牙语",
        "Mexican Spanish": "墨西哥西班牙语",
        "Brazilian Portuguese": "巴西葡萄牙语",
        "German": "德语",
        "Cologne German": "科隆德语",
        "Dutch": "荷兰语",
        "Turkish": "土耳其语",
        "Afrikaans": "南非荷兰语",
        "Romanian": "罗马尼亚语",
        "Russian": "俄语",
        "Simplified Chinese": "简体中文",
        "Traditional Chinese": "繁体中文",
        "Thai": "泰语",
        "Venezuelan Spanish": "委内瑞拉西班牙语",
        "Argentinian Spanish": "阿根廷西班牙语",
        "Vietnamese": "越南语",
        "Australian English": "澳大利亚英语",
        "Language": "语言",
        "Select language": "选择语言",
        "OK": "确定",
        "Cancel": "取消",
        "Exit": "退出",
        "Apply": "应用",
        "Yes": "是",
        "No": "否",
    },
    # ---- TRADITIONAL CHINESE ----
    "zh_TW": {
        "American": "美式英語",
        "English": "英式英語",
        "Spanish": "西班牙語",
        "Mexican Spanish": "墨西哥西班牙語",
        "Brazilian Portuguese": "巴西葡萄牙語",
        "German": "德語",
        "Cologne German": "科隆德語",
        "Dutch": "荷蘭語",
        "Turkish": "土耳其語",
        "Afrikaans": "南非荷蘭語",
        "Romanian": "羅馬尼亞語",
        "Russian": "俄語",
        "Simplified Chinese": "簡體中文",
        "Traditional Chinese": "繁體中文",
        "Thai": "泰語",
        "Venezuelan Spanish": "委內瑞拉西班牙語",
        "Argentinian Spanish": "阿根廷西班牙語",
        "Vietnamese": "越南語",
        "Australian English": "澳大利亞英語",
        "Language": "語言",
        "Select language": "選擇語言",
        "OK": "確定",
        "Cancel": "取消",
        "Exit": "退出",
        "Apply": "應用",
        "Yes": "是",
        "No": "否",
    },
    # ---- THAI ----
    "th_TH": {
        "American": "อังกฤษแบบอเมริกัน",
        "English": "อังกฤษแบบบริติช",
        "Spanish": "สเปน",
        "Mexican Spanish": "สเปนเม็กซิกัน",
        "Brazilian Portuguese": "โปรตุเกสบราซิล",
        "German": "เยอรมัน",
        "Cologne German": "เยอรมันโคโลญ",
        "Dutch": "ดัตช์",
        "Turkish": "ตุรกี",
        "Afrikaans": "แอฟริกันส์",
        "Romanian": "โรมาเนีย",
        "Russian": "รัสเซีย",
        "Simplified Chinese": "จีนตัวย่อ",
        "Traditional Chinese": "จีนตัวเต็ม",
        "Thai": "ไทย",
        "Venezuelan Spanish": "สเปนเวเนซุเอลา",
        "Argentinian Spanish": "สเปนอาร์เจนตินา",
        "Vietnamese": "เวียดนาม",
        "Australian English": "อังกฤษออสเตรเลีย",
        "Language": "ภาษา",
        "Select language": "เลือกภาษา",
        "OK": "ตกลง",
        "Cancel": "ยกเลิก",
        "Exit": "ออก",
        "Apply": "นำไปใช้",
        "Yes": "ใช่",
        "No": "ไม่",
    },
    # ---- VIETNAMESE ----
    "vi_VN": {
        "American": "Tiếng Anh Mỹ",
        "English": "Tiếng Anh Anh",
        "Spanish": "Tiếng Tây Ban Nha",
        "Mexican Spanish": "Tiếng Tây Ban Nha Mexico",
        "Brazilian Portuguese": "Tiếng Bồ Đào Nha Brazil",
        "German": "Tiếng Đức",
        "Cologne German": "Tiếng Đức Cologne",
        "Dutch": "Tiếng Hà Lan",
        "Turkish": "Tiếng Thổ Nhĩ Kỳ",
        "Afrikaans": "Tiếng Afrikaans",
        "Romanian": "Tiếng Rumani",
        "Russian": "Tiếng Nga",
        "Simplified Chinese": "Tiếng Trung giản thể",
        "Traditional Chinese": "Tiếng Trung phồn thể",
        "Thai": "Tiếng Thái",
        "Venezuelan Spanish": "Tiếng Tây Ban Nha Venezuela",
        "Argentinian Spanish": "Tiếng Tây Ban Nha Argentina",
        "Vietnamese": "Tiếng Việt",
        "Australian English": "Tiếng Anh Úc",
        "Language": "Ngôn ngữ",
        "Select language": "Chọn ngôn ngữ",
        "OK": "OK",
        "Cancel": "Hủy",
        "Exit": "Thoát",
        "Apply": "Áp dụng",
        "Yes": "Có",
        "No": "Không",
    },
    # ---- Add more dialects as needed, or use the closest fallback ----
}
