LANG_CODES = {
    "American":            "en_US",
    "English":             "en_GB",
    "Spanish":             "es_ES",
    "Mexican Spanish":     "es_MX",
    "Brazilian Portuguese":"pt_BR",
    "German":              "de_DE",
    "Cologne German":      "de_KO",
    "Dutch":               "nl_NL",
    "Turkish":             "tr_TR",
    "Afrikaans":           "af_ZA",
    "Romanian":            "ro_RO",
    "Russian":             "ru_RU",
    "Simplified Chinese":  "zh_CN",
    "Traditional Chinese": "zh_TW",
    "Thai":                "th_TH",
    "Venezuelan Spanish":  "es_VE",
    "Argentinian Spanish": "es_AR",
    "Vietnamese":          "vi_VN",
    "Australian English":  "en_AU",
}

ALL_KEYS = [
    *LANG_CODES.keys(),
    "Language",
    "Select language",
    "OK",
    "Cancel",
    "Exit",
    "Apply",
    "Yes",
    "No",
    # GUI-specific
    "Root Folder:",
    "Mapping File:",
    "Browse",
    "Last Monthly  (F)",
    "Prev Monthly  (E)",
    "Last Weekly   (M)",
    "Prev Weekly   (L)",
    "Last Daily    (Q)",
    "Prev Daily    (P)",
    "Shift Values:",
    "Monthly (D→C–F→E)",
    "Weekly  (I→H–M→L)",
    "Daily   (P→O–Q→P)",
    "Run",
    "Done",
    "Complete",
    "skipped",
]

TRANSLATIONS = {
    # ---- ENGLISH (American) ----
    "en_US": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
        "Root Folder:": "Root Folder:",
        "Mapping File:": "Mapping File:",
        "Browse": "Browse",
        "Last Monthly  (F)": "Last Monthly  (F)",
        "Prev Monthly  (E)": "Prev Monthly  (E)",
        "Last Weekly   (M)": "Last Weekly   (M)",
        "Prev Weekly   (L)": "Prev Weekly   (L)",
        "Last Daily    (Q)": "Last Daily    (Q)",
        "Prev Daily    (P)": "Prev Daily    (P)",
        "Shift Values:": "Shift Values:",
        "Monthly (D→C–F→E)": "Monthly (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Weekly  (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Daily   (P→O–Q→P)",
        "Run": "Run",
        "Done": "Done",
        "Complete": "Complete",
        "skipped": "skipped",
        "Column\nUpdate\nOptions": "Column\nUpdate\nOptions"
    },
    # ---- ENGLISH (British) ----
    "en_GB": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
        "Root Folder:": "Root Folder:",
        "Mapping File:": "Mapping File:",
        "Browse": "Browse",
        "Last Monthly  (F)": "Last Monthly  (F)",
        "Prev Monthly  (E)": "Prev Monthly  (E)",
        "Last Weekly   (M)": "Last Weekly   (M)",
        "Prev Weekly   (L)": "Prev Weekly   (L)",
        "Last Daily    (Q)": "Last Daily    (Q)",
        "Prev Daily    (P)": "Prev Daily    (P)",
        "Shift Values:": "Shift Values:",
        "Monthly (D→C–F→E)": "Monthly (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Weekly  (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Daily   (P→O–Q→P)",
        "Run": "Run",
        "Done": "Done",
        "Complete": "Complete",
        "skipped": "skipped",
        "Column\nUpdate\nOptions": "Column\nUpdate\nOptions"
    },
    # ---- ENGLISH (Australian) ----
    "en_AU": {
        **{name: name for name in LANG_CODES},
        "Language": "Language",
        "Select language": "Select language",
        "OK": "OK",
        "Cancel": "Cancel",
        "Exit": "Exit",
        "Apply": "Apply",
        "Yes": "Yes",
        "No": "No",
        "Root Folder:": "Root Folder:",
        "Mapping File:": "Mapping File:",
        "Browse": "Browse",
        "Last Monthly  (F)": "Last Monthly  (F)",
        "Prev Monthly  (E)": "Prev Monthly  (E)",
        "Last Weekly   (M)": "Last Weekly   (M)",
        "Prev Weekly   (L)": "Prev Weekly   (L)",
        "Last Daily    (Q)": "Last Daily    (Q)",
        "Prev Daily    (P)": "Prev Daily    (P)",
        "Shift Values:": "Shift Values:",
        "Monthly (D→C–F→E)": "Monthly (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Weekly  (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Daily   (P→O–Q→P)",
        "Run": "Run",
        "Done": "Done",
        "Complete": "Complete",
        "skipped": "skipped",
        "Column\nUpdate\nOptions": "Column\nUpdate\nOptions"
    },
    # ---- SPANISH (Spain) ----
    "es_ES": {
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
        "Root Folder:": "Carpeta raíz:",
        "Mapping File:": "Archivo de mapeo:",
        "Browse": "Examinar",
        "Last Monthly  (F)": "Último mensual (F)",
        "Prev Monthly  (E)": "Mensual anterior (E)",
        "Last Weekly   (M)": "Último semanal (M)",
        "Prev Weekly   (L)": "Semanal anterior (L)",
        "Last Daily    (Q)": "Último diario (Q)",
        "Prev Daily    (P)": "Diario anterior (P)",
        "Shift Values:": "Desplazar valores:",
        "Monthly (D→C–F→E)": "Mensual (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Semanal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Diario (P→O–Q→P)",
        "Run": "Ejecutar",
        "Done": "Hecho",
        "Complete": "Completo",
        "skipped": "omitido",
        "Column\nUpdate\nOptions": "Columna\nActualizar\nOpciones"
    },
    # ---- MEXICAN SPANISH ----
    "es_MX": {
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
        "Root Folder:": "Carpeta raíz:",
        "Mapping File:": "Archivo de mapeo:",
        "Browse": "Examinar",
        "Last Monthly  (F)": "Último mensual (F)",
        "Prev Monthly  (E)": "Mensual anterior (E)",
        "Last Weekly   (M)": "Último semanal (M)",
        "Prev Weekly   (L)": "Semanal anterior (L)",
        "Last Daily    (Q)": "Último diario (Q)",
        "Prev Daily    (P)": "Diario anterior (P)",
        "Shift Values:": "Desplazar valores:",
        "Monthly (D→C–F→E)": "Mensual (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Semanal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Diario (P→O–Q→P)",
        "Run": "Ejecutar",
        "Done": "Hecho",
        "Complete": "Completo",
        "skipped": "omitido",
        "Column\nUpdate\nOptions": "Columna\nActualizar\nOpciones"
    },
    # ---- BRAZILIAN PORTUGUESE ----
    "pt_BR": {
        "American": "Inglês americano",
        "English": "Inglês britânico",
        "Spanish": "Espanhol",
        "Mexican Spanish": "Espanhol mexicano",
        "Brazilian Portuguese": "Português brasileiro",
        "German": "Alemão",
        "Cologne German": "Alemão de Colônia",
        "Dutch": "Holandês",
        "Turkish": "Turco",
        "Afrikaans": "Africâner",
        "Romanian": "Romeno",
        "Russian": "Russo",
        "Simplified Chinese": "Chinês simplificado",
        "Traditional Chinese": "Chinês tradicional",
        "Thai": "Tailandês",
        "Venezuelan Spanish": "Espanhol venezuelano",
        "Argentinian Spanish": "Espanhol argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglês australiano",
        "Language": "Idioma",
        "Select language": "Selecionar idioma",
        "OK": "OK",
        "Cancel": "Cancelar",
        "Exit": "Sair",
        "Apply": "Aplicar",
        "Yes": "Sim",
        "No": "Não",
        "Root Folder:": "Pasta raiz:",
        "Mapping File:": "Arquivo de mapeamento:",
        "Browse": "Procurar",
        "Last Monthly  (F)": "Último mensal (F)",
        "Prev Monthly  (E)": "Mensal anterior (E)",
        "Last Weekly   (M)": "Último semanal (M)",
        "Prev Weekly   (L)": "Semanal anterior (L)",
        "Last Daily    (Q)": "Último diário (Q)",
        "Prev Daily    (P)": "Diário anterior (P)",
        "Shift Values:": "Deslocar valores:",
        "Monthly (D→C–F→E)": "Mensal (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Semanal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Diário (P→O–Q→P)",
        "Run": "Executar",
        "Done": "Concluído",
        "Complete": "Completo",
        "skipped": "ignorado",
        "Column\nUpdate\nOptions": "Coluna\nAtualizar\nOpções"
    },
    # ---- GERMAN ----
    "de_DE": {
        "American": "Amerikanisches Englisch",
        "English": "Englisch",
        "Spanish": "Spanisch",
        "Mexican Spanish": "Mexikanisches Spanisch",
        "Brazilian Portuguese": "Brasilianisches Portugiesisch",
        "German": "Deutsch",
        "Cologne German": "Kölsch",
        "Dutch": "Niederländisch",
        "Turkish": "Türkisch",
        "Afrikaans": "Afrikaans",
        "Romanian": "Rumänisch",
        "Russian": "Russisch",
        "Simplified Chinese": "Vereinfachtes Chinesisch",
        "Traditional Chinese": "Traditionelles Chinesisch",
        "Thai": "Thailändisch",
        "Venezuelan Spanish": "Venezolanisches Spanisch",
        "Argentinian Spanish": "Argentinisches Spanisch",
        "Vietnamese": "Vietnamesisch",
        "Australian English": "Australisches Englisch",
        "Language": "Sprache",
        "Select language": "Sprache auswählen",
        "OK": "OK",
        "Cancel": "Abbrechen",
        "Exit": "Beenden",
        "Apply": "Übernehmen",
        "Yes": "Ja",
        "No": "Nein",
        "Root Folder:": "Stammordner:",
        "Mapping File:": "Mapping-Datei:",
        "Browse": "Durchsuchen",
        "Last Monthly  (F)": "Letzter Monat (F)",
        "Prev Monthly  (E)": "Vorheriger Monat (E)",
        "Last Weekly   (M)": "Letzte Woche (M)",
        "Prev Weekly   (L)": "Vorherige Woche (L)",
        "Last Daily    (Q)": "Letzter Tag (Q)",
        "Prev Daily    (P)": "Vorheriger Tag (P)",
        "Shift Values:": "Werte verschieben:",
        "Monthly (D→C–F→E)": "Monatlich (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Wöchentlich (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Täglich (P→O–Q→P)",
        "Run": "Ausführen",
        "Done": "Fertig",
        "Complete": "Vollständig",
        "skipped": "übersprungen",
        "Column\nUpdate\nOptions": "Spalte\nAktualisieren\nOptionen"
    },
    # ---- COLOGNE GERMAN ----
    "de_KO": {
        "American": "Amerikanisches Englisch",
        "English": "Englisch",
        "Spanish": "Spanisch",
        "Mexican Spanish": "Mexikanisches Spanisch",
        "Brazilian Portuguese": "Brasilianisches Portugiesisch",
        "German": "Deutsch",
        "Cologne German": "Kölsch",
        "Dutch": "Niederländisch",
        "Turkish": "Türkisch",
        "Afrikaans": "Afrikaans",
        "Romanian": "Rumänisch",
        "Russian": "Russisch",
        "Simplified Chinese": "Vereinfachtes Chinesisch",
        "Traditional Chinese": "Traditionelles Chinesisch",
        "Thai": "Thailändisch",
        "Venezuelan Spanish": "Venezolanisches Spanisch",
        "Argentinian Spanish": "Argentinisches Spanisch",
        "Vietnamese": "Vietnamesisch",
        "Australian English": "Australisches Englisch",
        "Language": "Sprache",
        "Select language": "Sprache auswählen",
        "OK": "OK",
        "Cancel": "Abbrechen",
        "Exit": "Beenden",
        "Apply": "Übernehmen",
        "Yes": "Ja",
        "No": "Nein",
        "Root Folder:": "Stammordner:",
        "Mapping File:": "Mapping-Datei:",
        "Browse": "Durchsuchen",
        "Last Monthly  (F)": "Letzter Monat (F)",
        "Prev Monthly  (E)": "Vorheriger Monat (E)",
        "Last Weekly   (M)": "Letzte Woche (M)",
        "Prev Weekly   (L)": "Vorherige Woche (L)",
        "Last Daily    (Q)": "Letzter Tag (Q)",
        "Prev Daily    (P)": "Vorheriger Tag (P)",
        "Shift Values:": "Werte verschieben:",
        "Monthly (D→C–F→E)": "Monatlich (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Wöchentlich (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Täglich (P→O–Q→P)",
        "Run": "Ausführen",
        "Done": "Fertig",
        "Complete": "Vollständig",
        "skipped": "übersprungen",
        "Column\nUpdate\nOptions": "Spalte\nAktualisieren\nOptionen"
    },
    # ---- DUTCH ----
    "nl_NL": {
        "American": "Amerikaans Engels",
        "English": "Brits Engels",
        "Spanish": "Spaans",
        "Mexican Spanish": "Mexicaans Spaans",
        "Brazilian Portuguese": "Braziliaans Portugees",
        "German": "Duits",
        "Cologne German": "Keuls",
        "Dutch": "Nederlands",
        "Turkish": "Turks",
        "Afrikaans": "Afrikaans",
        "Romanian": "Roemeens",
        "Russian": "Russisch",
        "Simplified Chinese": "Vereenvoudigd Chinees",
        "Traditional Chinese": "Traditioneel Chinees",
        "Thai": "Thais",
        "Venezuelan Spanish": "Venezolaans Spaans",
        "Argentinian Spanish": "Argentijns Spaans",
        "Vietnamese": "Vietnamees",
        "Australian English": "Australisch Engels",
        "Language": "Taal",
        "Select language": "Taal selecteren",
        "OK": "OK",
        "Cancel": "Annuleren",
        "Exit": "Afsluiten",
        "Apply": "Toepassen",
        "Yes": "Ja",
        "No": "Nee",
        "Root Folder:": "Hoofdmap:",
        "Mapping File:": "Koppelingsbestand:",
        "Browse": "Bladeren",
        "Last Monthly  (F)": "Laatste maand (F)",
        "Prev Monthly  (E)": "Vorige maand (E)",
        "Last Weekly   (M)": "Laatste week (M)",
        "Prev Weekly   (L)": "Vorige week (L)",
        "Last Daily    (Q)": "Laatste dag (Q)",
        "Prev Daily    (P)": "Vorige dag (P)",
        "Shift Values:": "Waarden verschuiven:",
        "Monthly (D→C–F→E)": "Maandelijks (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Wekelijks (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Dagelijks (P→O–Q→P)",
        "Run": "Uitvoeren",
        "Done": "Klaar",
        "Complete": "Voltooid",
        "skipped": "overgeslagen",
        "Column\nUpdate\nOptions": "Kolom\nBijwerken\nOpties"
    },
    # ---- TURKISH ----
    "tr_TR": {
        "American": "Amerikan İngilizcesi",
        "English": "İngilizce",
        "Spanish": "İspanyolca",
        "Mexican Spanish": "Meksika İspanyolcası",
        "Brazilian Portuguese": "Brezilya Portekizcesi",
        "German": "Almanca",
        "Cologne German": "Köln Almancası",
        "Dutch": "Felemenkçe",
        "Turkish": "Türkçe",
        "Afrikaans": "Afrikanca",
        "Romanian": "Rumence",
        "Russian": "Rusça",
        "Simplified Chinese": "Basitleştirilmiş Çince",
        "Traditional Chinese": "Geleneksel Çince",
        "Thai": "Tayca",
        "Venezuelan Spanish": "Venezuela İspanyolcası",
        "Argentinian Spanish": "Arjantin İspanyolcası",
        "Vietnamese": "Vietnamca",
        "Australian English": "Avustralya İngilizcesi",
        "Language": "Dil",
        "Select language": "Dil seçin",
        "OK": "Tamam",
        "Cancel": "İptal",
        "Exit": "Çıkış",
        "Apply": "Uygula",
        "Yes": "Evet",
        "No": "Hayır",
        "Root Folder:": "Kök Dizin:",
        "Mapping File:": "Eşleme Dosyası:",
        "Browse": "Gözat",
        "Last Monthly  (F)": "Son Aylık (F)",
        "Prev Monthly  (E)": "Önceki Aylık (E)",
        "Last Weekly   (M)": "Son Haftalık (M)",
        "Prev Weekly   (L)": "Önceki Haftalık (L)",
        "Last Daily    (Q)": "Son Günlük (Q)",
        "Prev Daily    (P)": "Önceki Günlük (P)",
        "Shift Values:": "Değerleri Kaydır:",
        "Monthly (D→C–F→E)": "Aylık (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Haftalık (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Günlük (P→O–Q→P)",
        "Run": "Çalıştır",
        "Done": "Bitti",
        "Complete": "Tamamlandı",
        "skipped": "atlandı",
        "Column\nUpdate\nOptions": "Sütun\nGüncelle\nSeçenekler"
    },
    # ---- AFRIKAANS ----
    "af_ZA": {
        "American": "Amerikaanse Engels",
        "English": "Britse Engels",
        "Spanish": "Spaans",
        "Mexican Spanish": "Meksikaanse Spaans",
        "Brazilian Portuguese": "Brasiliaanse Portugees",
        "German": "Duits",
        "Cologne German": "Keuls",
        "Dutch": "Nederlands",
        "Turkish": "Turks",
        "Afrikaans": "Afrikaans",
        "Romanian": "Roemeens",
        "Russian": "Russies",
        "Simplified Chinese": "Vereenvoudigde Sjinees",
        "Traditional Chinese": "Tradisionele Sjinees",
        "Thai": "Thai",
        "Venezuelan Spanish": "Venezolaanse Spaans",
        "Argentinian Spanish": "Argentynse Spaans",
        "Vietnamese": "Viëtnamees",
        "Australian English": "Australiese Engels",
        "Language": "Taal",
        "Select language": "Kies taal",
        "OK": "OK",
        "Cancel": "Kanselleer",
        "Exit": "Verlaat",
        "Apply": "Pas toe",
        "Yes": "Ja",
        "No": "Nee",
        "Root Folder:": "Gids:",
        "Mapping File:": "Koppel-lêer:",
        "Browse": "Blaai",
        "Last Monthly  (F)": "Laaste maandeliks (F)",
        "Prev Monthly  (E)": "Vorige maandeliks (E)",
        "Last Weekly   (M)": "Laaste weekliks (M)",
        "Prev Weekly   (L)": "Vorige weekliks (L)",
        "Last Daily    (Q)": "Laaste daagliks (Q)",
        "Prev Daily    (P)": "Vorige daagliks (P)",
        "Shift Values:": "Verskuif waardes:",
        "Monthly (D→C–F→E)": "Maandeliks (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Weekliks (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Daagliks (P→O–Q→P)",
        "Run": "Begin",
        "Done": "Klaar",
        "Complete": "Voltooi",
        "skipped": "oorgegaan",
        "Column\nUpdate\nOptions": "Kolom\nOpdateer\nOpsies"
    },
    # ---- ROMANIAN ----
    "ro_RO": {
        "American": "Americană",
        "English": "Engleză",
        "Spanish": "Spaniolă",
        "Mexican Spanish": "Spaniolă mexicană",
        "Brazilian Portuguese": "Portugheză braziliană",
        "German": "Germană",
        "Cologne German": "Germană din Köln",
        "Dutch": "Olandeză",
        "Turkish": "Turcă",
        "Afrikaans": "Afrikaans",
        "Romanian": "Română",
        "Russian": "Rusă",
        "Simplified Chinese": "Chineză simplificată",
        "Traditional Chinese": "Chineză tradițională",
        "Thai": "Thailandeză",
        "Venezuelan Spanish": "Spaniolă venezueleană",
        "Argentinian Spanish": "Spaniolă argentiniană",
        "Vietnamese": "Vietnameză",
        "Australian English": "Engleză australiană",
        "Language": "Limbă",
        "Select language": "Selectează limba",
        "OK": "OK",
        "Cancel": "Anulează",
        "Exit": "Ieșire",
        "Apply": "Aplică",
        "Yes": "Da",
        "No": "Nu",
        "Root Folder:": "Director rădăcină:",
        "Mapping File:": "Fișier de mapare:",
        "Browse": "Răsfoiește",
        "Last Monthly  (F)": "Ultima lunară (F)",
        "Prev Monthly  (E)": "Lunară precedentă (E)",
        "Last Weekly   (M)": "Ultima săptămânală (M)",
        "Prev Weekly   (L)": "Săptămânală precedentă (L)",
        "Last Daily    (Q)": "Ultima zilnică (Q)",
        "Prev Daily    (P)": "Zilnică precedentă (P)",
        "Shift Values:": "Valori de mutat:",
        "Monthly (D→C–F→E)": "Lunar (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Săptămânal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Zilnic (P→O–Q→P)",
        "Run": "Rulează",
        "Done": "Gata",
        "Complete": "Complet",
        "skipped": "sărite",
        "Column\nUpdate\nOptions": "Opțiuni\nActualizare\nColoană"
    },
    # ---- RUSSIAN ----
    "ru_RU": {
        "American": "Американский английский",
        "English": "Британский английский",
        "Spanish": "Испанский",
        "Mexican Spanish": "Мексиканский испанский",
        "Brazilian Portuguese": "Бразильский португальский",
        "German": "Немецкий",
        "Cologne German": "Кёльнский диалект",
        "Dutch": "Голландский",
        "Turkish": "Турецкий",
        "Afrikaans": "Африкаанс",
        "Romanian": "Румынский",
        "Russian": "Русский",
        "Simplified Chinese": "Упрощённый китайский",
        "Traditional Chinese": "Традиционный китайский",
        "Thai": "Тайский",
        "Venezuelan Spanish": "Венесуэльский испанский",
        "Argentinian Spanish": "Аргентинский испанский",
        "Vietnamese": "Вьетнамский",
        "Australian English": "Австралийский английский",
        "Language": "Язык",
        "Select language": "Выберите язык",
        "OK": "ОК",
        "Cancel": "Отмена",
        "Exit": "Выход",
        "Apply": "Применить",
        "Yes": "Да",
        "No": "Нет",
        "Root Folder:": "Корневая папка:",
        "Mapping File:": "Файл сопоставления:",
        "Browse": "Обзор",
        "Last Monthly  (F)": "Последний месяц (F)",
        "Prev Monthly  (E)": "Предыдущий месяц (E)",
        "Last Weekly   (M)": "Последняя неделя (M)",
        "Prev Weekly   (L)": "Предыдущая неделя (L)",
        "Last Daily    (Q)": "Последний день (Q)",
        "Prev Daily    (P)": "Предыдущий день (P)",
        "Shift Values:": "Сдвиг значений:",
        "Monthly (D→C–F→E)": "Ежемесячно (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Еженедельно (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Ежедневно (P→O–Q→P)",
        "Run": "Запуск",
        "Done": "Готово",
        "Complete": "Выполнено",
        "skipped": "пропущено",
        "Column\nUpdate\nOptions": "Колонка\nОбновить\nОпции"
    },
    # ---- SIMPLIFIED CHINESE ----
    "zh_CN": {
        "American": "美式英语",
        "English": "英式英语",
        "Spanish": "西班牙语",
        "Mexican Spanish": "墨西哥西班牙语",
        "Brazilian Portuguese": "巴西葡萄牙语",
        "German": "德语",
        "Cologne German": "科隆德语",
        "Dutch": "荷兰语",
        "Turkish": "土耳其语",
        "Afrikaans": "南非荷兰语",
        "Romanian": "罗马尼亚语",
        "Russian": "俄语",
        "Simplified Chinese": "简体中文",
        "Traditional Chinese": "繁体中文",
        "Thai": "泰语",
        "Venezuelan Spanish": "委内瑞拉西班牙语",
        "Argentinian Spanish": "阿根廷西班牙语",
        "Vietnamese": "越南语",
        "Australian English": "澳大利亚英语",
        "Language": "语言",
        "Select language": "选择语言",
        "OK": "确定",
        "Cancel": "取消",
        "Exit": "退出",
        "Apply": "应用",
        "Yes": "是",
        "No": "否",
        "Root Folder:": "根文件夹：",
        "Mapping File:": "映射文件：",
        "Browse": "浏览",
        "Last Monthly  (F)": "最近月度 (F)",
        "Prev Monthly  (E)": "上次月度 (E)",
        "Last Weekly   (M)": "最近周度 (M)",
        "Prev Weekly   (L)": "上次周度 (L)",
        "Last Daily    (Q)": "最近每日 (Q)",
        "Prev Daily    (P)": "上次每日 (P)",
        "Shift Values:": "移动值：",
        "Monthly (D→C–F→E)": "月度 (D→C–F→E)",
        "Weekly  (I→H–M→L)": "周度 (I→H–M→L)",
        "Daily   (P→O–Q→P)": "每日 (P→O–Q→P)",
        "Run": "运行",
        "Done": "完成",
        "Complete": "完成",
        "skipped": "已跳过",
        "Column\nUpdate\nOptions": "列\n更新\n选项"
    },
    # ---- TRADITIONAL CHINESE ----
    "zh_TW": {
        "American": "美式英語",
        "English": "英式英語",
        "Spanish": "西班牙語",
        "Mexican Spanish": "墨西哥西班牙語",
        "Brazilian Portuguese": "巴西葡萄牙語",
        "German": "德語",
        "Cologne German": "科隆德語",
        "Dutch": "荷蘭語",
        "Turkish": "土耳其語",
        "Afrikaans": "南非荷蘭語",
        "Romanian": "羅馬尼亞語",
        "Russian": "俄語",
        "Simplified Chinese": "簡體中文",
        "Traditional Chinese": "繁體中文",
        "Thai": "泰語",
        "Venezuelan Spanish": "委內瑞拉西班牙語",
        "Argentinian Spanish": "阿根廷西班牙語",
        "Vietnamese": "越南語",
        "Australian English": "澳大利亞英語",
        "Language": "語言",
        "Select language": "選擇語言",
        "OK": "確定",
        "Cancel": "取消",
        "Exit": "退出",
        "Apply": "應用",
        "Yes": "是",
        "No": "否",
        "Root Folder:": "根目錄：",
        "Mapping File:": "映射文件：",
        "Browse": "瀏覽",
        "Last Monthly  (F)": "最近每月 (F)",
        "Prev Monthly  (E)": "上次每月 (E)",
        "Last Weekly   (M)": "最近每週 (M)",
        "Prev Weekly   (L)": "上次每週 (L)",
        "Last Daily    (Q)": "最近每日 (Q)",
        "Prev Daily    (P)": "上次每日 (P)",
        "Shift Values:": "移動值：",
        "Monthly (D→C–F→E)": "每月 (D→C–F→E)",
        "Weekly  (I→H–M→L)": "每週 (I→H–M→L)",
        "Daily   (P→O–Q→P)": "每日 (P→O–Q→P)",
        "Run": "執行",
        "Done": "完成",
        "Complete": "完成",
        "skipped": "已跳過",
        "Column\nUpdate\nOptions": "欄\n更新\n選項"
    },
    # ---- THAI ----
    "th_TH": {
        "American": "อังกฤษแบบอเมริกัน",
        "English": "อังกฤษแบบบริติช",
        "Spanish": "สเปน",
        "Mexican Spanish": "สเปนเม็กซิกัน",
        "Brazilian Portuguese": "โปรตุเกสบราซิล",
        "German": "เยอรมัน",
        "Cologne German": "เยอรมันโคโลญ",
        "Dutch": "ดัตช์",
        "Turkish": "ตุรกี",
        "Afrikaans": "แอฟริกันส์",
        "Romanian": "โรมาเนีย",
        "Russian": "รัสเซีย",
        "Simplified Chinese": "จีนตัวย่อ",
        "Traditional Chinese": "จีนตัวเต็ม",
        "Thai": "ไทย",
        "Venezuelan Spanish": "สเปนเวเนซุเอลา",
        "Argentinian Spanish": "สเปนอาร์เจนตินา",
        "Vietnamese": "เวียดนาม",
        "Australian English": "อังกฤษออสเตรเลีย",
        "Language": "ภาษา",
        "Select language": "เลือกภาษา",
        "OK": "ตกลง",
        "Cancel": "ยกเลิก",
        "Exit": "ออก",
        "Apply": "นำไปใช้",
        "Yes": "ใช่",
        "No": "ไม่",
        "Root Folder:": "โฟลเดอร์หลัก:",
        "Mapping File:": "ไฟล์แมปปิ้ง:",
        "Browse": "เรียกดู",
        "Last Monthly  (F)": "เดือนล่าสุด (F)",
        "Prev Monthly  (E)": "เดือนก่อนหน้า (E)",
        "Last Weekly   (M)": "สัปดาห์ล่าสุด (M)",
        "Prev Weekly   (L)": "สัปดาห์ก่อนหน้า (L)",
        "Last Daily    (Q)": "วันล่าสุด (Q)",
        "Prev Daily    (P)": "วันก่อนหน้า (P)",
        "Shift Values:": "เลื่อนค่า:",
        "Monthly (D→C–F→E)": "รายเดือน (D→C–F→E)",
        "Weekly  (I→H–M→L)": "รายสัปดาห์ (I→H–M→L)",
        "Daily   (P→O–Q→P)": "รายวัน (P→O–Q→P)",
        "Run": "รัน",
        "Done": "เสร็จสิ้น",
        "Complete": "สมบูรณ์",
        "skipped": "ข้าม",
        "Column\nUpdate\nOptions": "คอลัมน์\nอัปเดต\nตัวเลือก"
    },
    # ---- VENEZUELAN SPANISH ----
    "es_VE": {
        # Venezuela Spanish = Latin American Spanish, close to es_ES
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
        "Root Folder:": "Carpeta raíz:",
        "Mapping File:": "Archivo de mapeo:",
        "Browse": "Examinar",
        "Last Monthly  (F)": "Último mensual (F)",
        "Prev Monthly  (E)": "Mensual anterior (E)",
        "Last Weekly   (M)": "Último semanal (M)",
        "Prev Weekly   (L)": "Semanal anterior (L)",
        "Last Daily    (Q)": "Último diario (Q)",
        "Prev Daily    (P)": "Diario anterior (P)",
        "Shift Values:": "Desplazar valores:",
        "Monthly (D→C–F→E)": "Mensual (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Semanal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Diario (P→O–Q→P)",
        "Run": "Ejecutar",
        "Done": "Hecho",
        "Complete": "Completo",
        "skipped": "omitido",
        "Column\nUpdate\nOptions": "Columna\nActualizar\nOpciones"
    },
    # ---- ARGENTINIAN SPANISH ----
    "es_AR": {
        # Argentinian Spanish = close to es_ES
        "American": "Inglés americano",
        "English": "Inglés británico",
        "Spanish": "Español",
        "Mexican Spanish": "Español mexicano",
        "Brazilian Portuguese": "Portugués brasileño",
        "German": "Alemán",
        "Cologne German": "Alemán de Colonia",
        "Dutch": "Neerlandés",
        "Turkish": "Turco",
        "Afrikaans": "Afrikáans",
        "Romanian": "Rumano",
        "Russian": "Ruso",
        "Simplified Chinese": "Chino simplificado",
        "Traditional Chinese": "Chino tradicional",
        "Thai": "Tailandés",
        "Venezuelan Spanish": "Español venezolano",
        "Argentinian Spanish": "Español argentino",
        "Vietnamese": "Vietnamita",
        "Australian English": "Inglés australiano",
        "Language": "Idioma",
        "Select language": "Seleccionar idioma",
        "OK": "Aceptar",
        "Cancel": "Cancelar",
        "Exit": "Salir",
        "Apply": "Aplicar",
        "Yes": "Sí",
        "No": "No",
        "Root Folder:": "Carpeta raíz:",
        "Mapping File:": "Archivo de mapeo:",
        "Browse": "Examinar",
        "Last Monthly  (F)": "Último mensual (F)",
        "Prev Monthly  (E)": "Mensual anterior (E)",
        "Last Weekly   (M)": "Último semanal (M)",
        "Prev Weekly   (L)": "Semanal anterior (L)",
        "Last Daily    (Q)": "Último diario (Q)",
        "Prev Daily    (P)": "Diario anterior (P)",
        "Shift Values:": "Desplazar valores:",
        "Monthly (D→C–F→E)": "Mensual (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Semanal (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Diario (P→O–Q→P)",
        "Run": "Ejecutar",
        "Done": "Hecho",
        "Complete": "Completo",
        "skipped": "omitido",
        "Column\nUpdate\nOptions": "Columna\nActualizar\nOpciones"
    },
    # ---- VIETNAMESE ----
    "vi_VN": {
        "American": "Tiếng Anh Mỹ",
        "English": "Tiếng Anh Anh",
        "Spanish": "Tiếng Tây Ban Nha",
        "Mexican Spanish": "Tiếng Tây Ban Nha Mexico",
        "Brazilian Portuguese": "Tiếng Bồ Đào Nha Brazil",
        "German": "Tiếng Đức",
        "Cologne German": "Tiếng Đức Cologne",
        "Dutch": "Tiếng Hà Lan",
        "Turkish": "Tiếng Thổ Nhĩ Kỳ",
        "Afrikaans": "Tiếng Afrikaans",
        "Romanian": "Tiếng Rumani",
        "Russian": "Tiếng Nga",
        "Simplified Chinese": "Tiếng Trung giản thể",
        "Traditional Chinese": "Tiếng Trung phồn thể",
        "Thai": "Tiếng Thái",
        "Venezuelan Spanish": "Tiếng Tây Ban Nha Venezuela",
        "Argentinian Spanish": "Tiếng Tây Ban Nha Argentina",
        "Vietnamese": "Tiếng Việt",
        "Australian English": "Tiếng Anh Úc",
        "Language": "Ngôn ngữ",
        "Select language": "Chọn ngôn ngữ",
        "OK": "OK",
        "Cancel": "Hủy",
        "Exit": "Thoát",
        "Apply": "Áp dụng",
        "Yes": "Có",
        "No": "Không",
        "Root Folder:": "Thư mục gốc:",
        "Mapping File:": "Tệp ánh xạ:",
        "Browse": "Duyệt",
        "Last Monthly  (F)": "Tháng gần nhất (F)",
        "Prev Monthly  (E)": "Tháng trước (E)",
        "Last Weekly   (M)": "Tuần gần nhất (M)",
        "Prev Weekly   (L)": "Tuần trước (L)",
        "Last Daily    (Q)": "Ngày gần nhất (Q)",
        "Prev Daily    (P)": "Ngày trước (P)",
        "Shift Values:": "Dịch chuyển giá trị:",
        "Monthly (D→C–F→E)": "Hàng tháng (D→C–F→E)",
        "Weekly  (I→H–M→L)": "Hàng tuần (I→H–M→L)",
        "Daily   (P→O–Q→P)": "Hàng ngày (P→O–Q→P)",
        "Run": "Chạy",
        "Done": "Xong",
        "Complete": "Hoàn tất",
        "skipped": "bỏ qua",
        "Column\nUpdate\nOptions": "Cột\nCập nhật\nTùy chọn"
    },
}
